// <auto-generated />
namespace StuffFinder.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class MakeMe2AnInt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MakeMe2AnInt));
        
        string IMigrationMetadata.Id
        {
            get { return "201502080238266_MakeMe2AnInt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
